### ISSUE TITLE
1.15.1 Complains that `expect` is not a function?

### ISSUE THREAD

**Issue by ponelat** [mjackson/expect#74] opened 2016-03-11 17:17 UTC
Env: `mocha` + NodeJS 4.2.4 + npm@3.6.0

I notice the latest commit has tests against just this.... so I'll try to get the smallest failing case.

**Comment by ponelat** [comment] 2016-03-11 17:19
#### Update:

Just running this in node, it dies...
```js
var expect = require('expect') // v1.15.1
var expect(1).toEqual(1)
```

```
expect(1).toEqual(1)
^

TypeError: expect is not a function
    at Object.<anonymous> (/home/josh/projects/spec-map/tmp.js:2:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by ponelat** [comment] 2016-03-11 17:41
So I forked the repo, found that `./lib` works ... then I went into the node_modules/expect (in my project)
And found lib to be this....

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.restoreSpies = exports.isSpy = exports.spyOn = exports.createSpy = exports.extend = exports.assert = undefined;

var _Expectation = require('./Expectation');

var _Expectation2 = _interopRequireDefault(_Expectation);

var _SpyUtils = require('./SpyUtils');

var _assert = require('./assert');

var _assert2 = _interopRequireDefault(_assert);

var _extend = require('./extend');

var _extend2 = _interopRequireDefault(_extend);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function expect(actual) {
  return new _Expectation2.default(actual);
}

// TODO: Maybe remove these eventually?
expect.createSpy = _SpyUtils.createSpy;
expect.spyOn = _SpyUtils.spyOn;
expect.isSpy = _SpyUtils.isSpy;
expect.restoreSpies = _SpyUtils.restoreSpies;
expect.assert = _assert2.default;
expect.extend = _extend2.default;

exports.default = expect;
exports.assert = _assert2.default;
exports.extend = _extend2.default;
exports.createSpy = _SpyUtils.createSpy;
exports.spyOn = _SpyUtils.spyOn;
exports.isSpy = _SpyUtils.isSpy;
exports.restoreSpies = _SpyUtils.restoreSpies;
```

**Comment by rstacruz** [comment] 2016-03-11 17:41
Thanks for the report! This is a dupe of #72, due to be fixed soon.

**Closed by rstacruz** 2016-03-11 17:41 UTC

**Comment by ponelat** [comment] 2016-03-11 17:43
ah thanks... sorry I missed the original one.
